import 'dart:convert';
import 'dart:io';

import 'package:gaovmd/src/public_openapi_document.dart';

import '../lib/src/tool_bindings.dart';

/// Build-time only: production depends only on the public API client/models.
Future<void> main() async {
  final document = await loadPublicOpenApiDocument(
    File('../../schemas/openapi/gaovm-v1.yaml'),
  );
  final contracts = <String, Object?>{};
  for (final binding in toolBindings) {
    final path = (document['paths'] as Map)[binding.path] as Map;
    final operation = path[binding.method] as Map;
    final properties = <String, Object?>{};
    final required = <String>[];
    for (final raw in [
      ...?path['parameters'] as List?,
      ...?operation['parameters'] as List?,
    ]) {
      final parameter = _resolve(raw, document) as Map;
      final name = parameter['name'] == 'Idempotency-Key'
          ? 'idempotency_key'
          : parameter['name'] as String;
      if (!const {'path', 'query', 'header'}.contains(parameter['in'])) {
        throw StateError('unsupported MCP parameter: $name');
      }
      properties[name] = _resolve(parameter['schema'], document);
      if (parameter['required'] == true || name == 'idempotency_key') {
        required.add(name);
      }
    }
    if (operation['requestBody'] != null) {
      final body = _resolve(operation['requestBody'], document) as Map;
      properties['body'] = body['content']['application/json']['schema'];
      if (body['required'] == true) required.add('body');
    }
    properties['request_timeout_seconds'] = {
      'type': 'number',
      'exclusiveMinimum': 0,
      'maximum': 86400,
      'description':
          'Local HTTP deadline; 30 seconds by default. VM waits '
          'default to their explicit body timeout plus five seconds.',
    };
    contracts[binding.name] = {
      'name': binding.name,
      'description':
          '${operation['summary']}. Only the public API is used. '
          'Mutations return durable Operations; reuse idempotency_key on retry.',
      'inputSchema': {
        'type': 'object',
        'properties': properties,
        if (required.isNotEmpty) 'required': required,
        'additionalProperties': false,
      },
    };
  }
  final json = const JsonEncoder.withIndent('  ').convert(contracts);
  if (json.contains("'''")) throw StateError('invalid Dart string delimiter');
  stdout.write(
    '// Generated by tool/generate_contract.dart from the canonical\n'
    '// OpenAPI and VmSpec schemas. Do not edit by hand.\n'
    "const toolContractsJson = r'''\n$json\n''';\n",
  );
}

Object? _resolve(
  Object? value,
  Map<String, Object?> document, [
  int depth = 0,
]) {
  if (depth > 64) throw StateError('recursive public schema');
  if (value is List) {
    return value.map((item) => _resolve(item, document, depth + 1)).toList();
  }
  if (value is! Map) return value;
  if (value.containsKey(r'$ref')) {
    final reference = value[r'$ref'] as String;
    if (!reference.startsWith('#/')) {
      throw StateError('non-local public schema reference');
    }
    Object? target = document;
    for (final part in reference.substring(2).split('/')) {
      target =
          (target as Map)[part.replaceAll('~1', '/').replaceAll('~0', '~')];
    }
    return {
      ..._resolve(target, document, depth + 1) as Map,
      for (final entry in value.entries)
        if (entry.key != r'$ref')
          entry.key: _resolve(entry.value, document, depth + 1),
    };
  }
  return {
    for (final entry in value.entries)
      entry.key: _resolve(entry.value, document, depth + 1),
  };
}
