// Generated by tool/generate_contract.dart from the canonical
// OpenAPI and VmSpec schemas. Do not edit by hand.
const toolContractsJson = r'''
{
  "vm_list": {
    "name": "vm_list",
    "description": "List virtual machines. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "string",
          "minLength": 1,
          "maxLength": 512
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 200,
          "default": 50
        },
        "label_selector": {
          "type": "string",
          "maxLength": 4096
        },
        "sort": {
          "type": "string",
          "enum": [
            "created_at",
            "-created_at",
            "name",
            "-name",
            "id",
            "-id"
          ],
          "default": "created_at"
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "additionalProperties": false
    }
  },
  "vm_get": {
    "name": "vm_get",
    "description": "Get a virtual machine by immutable ID. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "vm_id": {
          "type": "string",
          "pattern": "^vm_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "vm_01J00000000000000000000000"
          ]
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "vm_id"
      ],
      "additionalProperties": false
    }
  },
  "vm_create": {
    "name": "vm_create",
    "description": "Create a virtual machine. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "idempotency_key": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        },
        "body": {
          "type": "object",
          "required": [
            "api_version",
            "kind",
            "metadata",
            "spec"
          ],
          "properties": {
            "api_version": {
              "const": "gaovm.io/v1alpha1"
            },
            "kind": {
              "const": "VirtualMachine"
            },
            "metadata": {
              "type": "object",
              "required": [
                "name"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 128
                },
                "labels": {
                  "type": "object",
                  "propertyNames": {
                    "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9._/-]*[A-Za-z0-9])?$"
                  },
                  "additionalProperties": {
                    "type": "string",
                    "maxLength": 253
                  },
                  "maxProperties": 64
                }
              },
              "additionalProperties": false
            },
            "spec": {
              "type": "object",
              "required": [
                "backend",
                "architecture",
                "cpu",
                "memory_bytes",
                "boot",
                "disks",
                "networks",
                "graphics",
                "serial",
                "guest_agent",
                "restart_policy"
              ],
              "properties": {
                "backend": {
                  "const": "vz",
                  "description": "Runtime backend. v1alpha1 supports Virtualization.framework only."
                },
                "architecture": {
                  "enum": [
                    "arm64"
                  ]
                },
                "guest_profile": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "minLength": 1,
                  "maxLength": 64,
                  "default": null
                },
                "cpu": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 64,
                  "x-gaovm-restart-required": true,
                  "description": "Validated again against the current host's VZ limits."
                },
                "memory_bytes": {
                  "type": "integer",
                  "minimum": 268435456,
                  "multipleOf": 1048576,
                  "x-gaovm-restart-required": true,
                  "description": "Memory in bytes, MiB aligned and validated against host VZ limits."
                },
                "boot": {
                  "oneOf": [
                    {
                      "type": "object",
                      "required": [
                        "type",
                        "kernel_image_id"
                      ],
                      "properties": {
                        "type": {
                          "const": "linux_kernel"
                        },
                        "kernel_image_id": {
                          "type": "string",
                          "pattern": "^img_[0-7][0-9A-HJKMNP-TV-Z]{25}$"
                        },
                        "initrd_image_id": {
                          "oneOf": [
                            {
                              "type": "string",
                              "pattern": "^img_[0-7][0-9A-HJKMNP-TV-Z]{25}$"
                            },
                            {
                              "type": "null"
                            }
                          ],
                          "default": null
                        },
                        "command_line": {
                          "type": "string",
                          "maxLength": 8192,
                          "default": ""
                        }
                      },
                      "additionalProperties": false
                    },
                    {
                      "type": "object",
                      "required": [
                        "type"
                      ],
                      "properties": {
                        "type": {
                          "const": "efi"
                        },
                        "variable_store": {
                          "enum": [
                            "managed",
                            "external"
                          ],
                          "default": "managed"
                        },
                        "variable_store_path": {
                          "type": "string",
                          "minLength": 1
                        }
                      },
                      "allOf": [
                        {
                          "if": {
                            "properties": {
                              "variable_store": {
                                "const": "external"
                              }
                            },
                            "required": [
                              "variable_store"
                            ]
                          },
                          "then": {
                            "required": [
                              "variable_store_path"
                            ]
                          }
                        }
                      ],
                      "additionalProperties": false,
                      "x-gaovm-priority": "P1"
                    }
                  ],
                  "x-gaovm-restart-required": true
                },
                "disks": {
                  "type": "array",
                  "minItems": 1,
                  "maxItems": 32,
                  "items": {
                    "type": "object",
                    "required": [
                      "id",
                      "source",
                      "writable"
                    ],
                    "properties": {
                      "id": {
                        "type": "string",
                        "pattern": "^[a-z][a-z0-9-]{0,31}$"
                      },
                      "source": {
                        "oneOf": [
                          {
                            "type": "object",
                            "required": [
                              "type",
                              "image_id"
                            ],
                            "properties": {
                              "type": {
                                "const": "managed_image"
                              },
                              "image_id": {
                                "type": "string",
                                "pattern": "^img_[0-7][0-9A-HJKMNP-TV-Z]{25}$"
                              }
                            },
                            "additionalProperties": false
                          },
                          {
                            "type": "object",
                            "required": [
                              "type",
                              "path"
                            ],
                            "properties": {
                              "type": {
                                "const": "external"
                              },
                              "path": {
                                "type": "string",
                                "minLength": 1,
                                "description": "Absolute host path, subject to server-side realpath and ownership checks."
                              }
                            },
                            "additionalProperties": false
                          }
                        ]
                      },
                      "writable": {
                        "type": "boolean"
                      }
                    },
                    "additionalProperties": false
                  },
                  "x-gaovm-restart-required": true
                },
                "networks": {
                  "type": "array",
                  "minItems": 1,
                  "maxItems": 8,
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "required": [
                          "id",
                          "mode"
                        ],
                        "properties": {
                          "id": {
                            "type": "string",
                            "pattern": "^[a-z][a-z0-9-]{0,31}$"
                          },
                          "mode": {
                            "const": "shared"
                          },
                          "mac_address": {
                            "type": "string",
                            "pattern": "^(?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$",
                            "description": "Stable locally administered MAC. The server assigns one when omitted."
                          }
                        },
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "required": [
                          "id",
                          "mode"
                        ],
                        "properties": {
                          "id": {
                            "type": "string",
                            "pattern": "^[a-z][a-z0-9-]{0,31}$"
                          },
                          "mode": {
                            "const": "none"
                          }
                        },
                        "additionalProperties": false
                      }
                    ]
                  },
                  "x-gaovm-restart-required": true
                },
                "graphics": {
                  "type": "object",
                  "required": [
                    "enabled"
                  ],
                  "properties": {
                    "enabled": {
                      "type": "boolean"
                    },
                    "width": {
                      "type": "integer",
                      "minimum": 320,
                      "maximum": 8192
                    },
                    "height": {
                      "type": "integer",
                      "minimum": 200,
                      "maximum": 8192
                    },
                    "pixels_per_inch": {
                      "type": "integer",
                      "minimum": 72,
                      "maximum": 600,
                      "default": 144
                    }
                  },
                  "allOf": [
                    {
                      "if": {
                        "properties": {
                          "enabled": {
                            "const": true
                          }
                        },
                        "required": [
                          "enabled"
                        ]
                      },
                      "then": {
                        "required": [
                          "width",
                          "height"
                        ]
                      }
                    }
                  ],
                  "additionalProperties": false,
                  "x-gaovm-restart-required": true
                },
                "serial": {
                  "type": "object",
                  "required": [
                    "enabled",
                    "capture"
                  ],
                  "properties": {
                    "enabled": {
                      "type": "boolean"
                    },
                    "capture": {
                      "type": "boolean"
                    }
                  },
                  "additionalProperties": false,
                  "x-gaovm-restart-required": true
                },
                "guest_agent": {
                  "type": "object",
                  "required": [
                    "enabled",
                    "required_for_ready"
                  ],
                  "properties": {
                    "enabled": {
                      "type": "boolean"
                    },
                    "required_for_ready": {
                      "type": "boolean"
                    },
                    "vsock_port": {
                      "type": "integer",
                      "minimum": 1024,
                      "maximum": 4294967295,
                      "default": 10777
                    }
                  },
                  "allOf": [
                    {
                      "if": {
                        "properties": {
                          "enabled": {
                            "const": false
                          }
                        },
                        "required": [
                          "enabled"
                        ]
                      },
                      "then": {
                        "properties": {
                          "required_for_ready": {
                            "const": false
                          }
                        }
                      }
                    }
                  ],
                  "additionalProperties": false
                },
                "restart_policy": {
                  "enum": [
                    "never",
                    "on_failure",
                    "always"
                  ]
                },
                "autostart": {
                  "type": "boolean",
                  "default": false,
                  "x-gaovm-priority": "P1"
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "idempotency_key",
        "body"
      ],
      "additionalProperties": false
    }
  },
  "vm_clone": {
    "name": "vm_clone",
    "description": "Clone one VM into a new VM. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "vm_id": {
          "type": "string",
          "pattern": "^vm_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "vm_01J00000000000000000000000"
          ]
        },
        "idempotency_key": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        },
        "body": {
          "type": "object",
          "required": [
            "name"
          ],
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1,
              "maxLength": 128
            },
            "labels": {
              "type": "object",
              "propertyNames": {
                "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9._/-]*[A-Za-z0-9])?$"
              },
              "additionalProperties": {
                "type": "string",
                "maxLength": 253
              },
              "maxProperties": 64
            }
          },
          "additionalProperties": false
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "vm_id",
        "idempotency_key",
        "body"
      ],
      "additionalProperties": false
    }
  },
  "vm_start": {
    "name": "vm_start",
    "description": "Start one VM. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "vm_id": {
          "type": "string",
          "pattern": "^vm_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "vm_01J00000000000000000000000"
          ]
        },
        "idempotency_key": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        },
        "body": {
          "type": "object",
          "properties": {
            "reason": {
              "type": "string",
              "maxLength": 1024
            },
            "deadline_at": {
              "type": "string",
              "format": "date-time"
            }
          },
          "additionalProperties": false
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "vm_id",
        "idempotency_key"
      ],
      "additionalProperties": false
    }
  },
  "vm_stop": {
    "name": "vm_stop",
    "description": "Gracefully stop one VM. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "vm_id": {
          "type": "string",
          "pattern": "^vm_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "vm_01J00000000000000000000000"
          ]
        },
        "idempotency_key": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        },
        "body": {
          "type": "object",
          "properties": {
            "reason": {
              "type": "string",
              "maxLength": 1024
            },
            "deadline_at": {
              "type": "string",
              "format": "date-time"
            }
          },
          "additionalProperties": false
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "vm_id",
        "idempotency_key"
      ],
      "additionalProperties": false
    }
  },
  "vm_wait": {
    "name": "vm_wait",
    "description": "Wait for an explicit VM condition. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "vm_id": {
          "type": "string",
          "pattern": "^vm_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "vm_01J00000000000000000000000"
          ]
        },
        "body": {
          "type": "object",
          "required": [
            "condition",
            "timeout_seconds"
          ],
          "properties": {
            "condition": {
              "enum": [
                "runtime_running",
                "guest_agent_ready",
                "guest_service_ready"
              ]
            },
            "service_name": {
              "type": "string",
              "minLength": 1
            },
            "timeout_seconds": {
              "type": "number",
              "exclusiveMinimum": 0,
              "maximum": 86400
            }
          },
          "allOf": [
            {
              "if": {
                "properties": {
                  "condition": {
                    "const": "guest_service_ready"
                  }
                }
              },
              "then": {
                "required": [
                  "service_name"
                ]
              }
            }
          ],
          "additionalProperties": false
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "vm_id",
        "body"
      ],
      "additionalProperties": false
    }
  },
  "vm_logs": {
    "name": "vm_logs",
    "description": "List stable references to bounded VM log files. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "vm_id": {
          "type": "string",
          "pattern": "^vm_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "vm_01J00000000000000000000000"
          ]
        },
        "kind": {
          "type": "string",
          "enum": [
            "driver",
            "serial",
            "guest"
          ]
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "vm_id"
      ],
      "additionalProperties": false
    }
  },
  "image_list": {
    "name": "image_list",
    "description": "List immutable images. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "string",
          "minLength": 1,
          "maxLength": 512
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 200,
          "default": 50
        },
        "label_selector": {
          "type": "string",
          "maxLength": 4096
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "additionalProperties": false
    }
  },
  "image_import": {
    "name": "image_import",
    "description": "Atomically import an immutable image. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "idempotency_key": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        },
        "body": {
          "type": "object",
          "required": [
            "source_path",
            "type",
            "architecture"
          ],
          "properties": {
            "source_path": {
              "type": "string",
              "minLength": 1,
              "description": "Host path validated using realpath and ownership checks."
            },
            "type": {
              "enum": [
                "linux-kernel",
                "initrd",
                "raw-disk",
                "gaoos-bundle"
              ]
            },
            "architecture": {
              "enum": [
                "arm64"
              ]
            },
            "guest_profile": {
              "type": [
                "string",
                "null"
              ]
            },
            "version": {
              "type": [
                "string",
                "null"
              ]
            },
            "build_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "channel": {
              "type": [
                "string",
                "null"
              ]
            },
            "labels": {
              "type": "object",
              "propertyNames": {
                "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9._/-]*[A-Za-z0-9])?$"
              },
              "additionalProperties": {
                "type": "string",
                "maxLength": 253
              },
              "maxProperties": 64
            }
          },
          "additionalProperties": false
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "idempotency_key",
        "body"
      ],
      "additionalProperties": false
    }
  },
  "guest_exec": {
    "name": "guest_exec",
    "description": "Execute an argv vector through the optional guest agent. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "vm_id": {
          "type": "string",
          "pattern": "^vm_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "vm_01J00000000000000000000000"
          ]
        },
        "idempotency_key": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        },
        "body": {
          "type": "object",
          "required": [
            "argv",
            "cwd",
            "env",
            "timeout_seconds",
            "capture"
          ],
          "properties": {
            "argv": {
              "type": "array",
              "minItems": 1,
              "maxItems": 1024,
              "items": {
                "type": "string",
                "maxLength": 131072
              }
            },
            "cwd": {
              "type": "string",
              "minLength": 1,
              "maxLength": 4096
            },
            "env": {
              "type": "object",
              "propertyNames": {
                "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
              },
              "additionalProperties": {
                "type": "string",
                "maxLength": 131072
              }
            },
            "timeout_seconds": {
              "type": "number",
              "exclusiveMinimum": 0,
              "maximum": 86400
            },
            "capture": {
              "type": "object",
              "required": [
                "stdout",
                "stderr",
                "max_inline_bytes"
              ],
              "properties": {
                "stdout": {
                  "type": "boolean"
                },
                "stderr": {
                  "type": "boolean"
                },
                "max_inline_bytes": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 1048576
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "vm_id",
        "idempotency_key",
        "body"
      ],
      "additionalProperties": false
    }
  },
  "operation_get": {
    "name": "operation_get",
    "description": "Get a durable operation. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "operation_id": {
          "type": "string",
          "pattern": "^op_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "op_01J00000000000000000000000"
          ]
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "operation_id"
      ],
      "additionalProperties": false
    }
  },
  "operation_cancel": {
    "name": "operation_cancel",
    "description": "Request cancellation of a cancellable operation. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "operation_id": {
          "type": "string",
          "pattern": "^op_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "op_01J00000000000000000000000"
          ]
        },
        "idempotency_key": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "operation_id",
        "idempotency_key"
      ],
      "additionalProperties": false
    }
  },
  "test_run": {
    "name": "test_run",
    "description": "Create a persistent TestRun orchestration resource. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "idempotency_key": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        },
        "body": {
          "type": "object",
          "required": [
            "source",
            "wait",
            "steps",
            "cleanup",
            "retain_on_failure"
          ],
          "properties": {
            "source": {
              "oneOf": [
                {
                  "type": "object",
                  "required": [
                    "image_id"
                  ],
                  "properties": {
                    "image_id": {
                      "type": "string",
                      "pattern": "^img_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
                      "examples": [
                        "img_01J00000000000000000000000"
                      ]
                    }
                  },
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "required": [
                    "template_vm_id"
                  ],
                  "properties": {
                    "template_vm_id": {
                      "type": "string",
                      "pattern": "^vm_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
                      "examples": [
                        "vm_01J00000000000000000000000"
                      ]
                    }
                  },
                  "additionalProperties": false
                }
              ]
            },
            "vm_overrides": {
              "type": "object",
              "minProperties": 1,
              "properties": {
                "backend": {
                  "const": "vz"
                },
                "architecture": {
                  "enum": [
                    "arm64"
                  ]
                },
                "guest_profile": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "cpu": {
                  "type": "integer",
                  "minimum": 1
                },
                "memory_bytes": {
                  "type": "integer",
                  "minimum": 268435456,
                  "multipleOf": 1048576
                },
                "boot": {
                  "oneOf": [
                    {
                      "type": "object",
                      "required": [
                        "type",
                        "kernel_image_id"
                      ],
                      "properties": {
                        "type": {
                          "const": "linux_kernel"
                        },
                        "kernel_image_id": {
                          "type": "string",
                          "pattern": "^img_[0-7][0-9A-HJKMNP-TV-Z]{25}$"
                        },
                        "initrd_image_id": {
                          "oneOf": [
                            {
                              "type": "string",
                              "pattern": "^img_[0-7][0-9A-HJKMNP-TV-Z]{25}$"
                            },
                            {
                              "type": "null"
                            }
                          ],
                          "default": null
                        },
                        "command_line": {
                          "type": "string",
                          "maxLength": 8192,
                          "default": ""
                        }
                      },
                      "additionalProperties": false
                    },
                    {
                      "type": "object",
                      "required": [
                        "type"
                      ],
                      "properties": {
                        "type": {
                          "const": "efi"
                        },
                        "variable_store": {
                          "enum": [
                            "managed",
                            "external"
                          ],
                          "default": "managed"
                        },
                        "variable_store_path": {
                          "type": "string",
                          "minLength": 1
                        }
                      },
                      "allOf": [
                        {
                          "if": {
                            "properties": {
                              "variable_store": {
                                "const": "external"
                              }
                            },
                            "required": [
                              "variable_store"
                            ]
                          },
                          "then": {
                            "required": [
                              "variable_store_path"
                            ]
                          }
                        }
                      ],
                      "additionalProperties": false,
                      "x-gaovm-priority": "P1"
                    }
                  ]
                },
                "disks": {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "object",
                    "required": [
                      "id",
                      "source",
                      "writable"
                    ],
                    "properties": {
                      "id": {
                        "type": "string",
                        "pattern": "^[a-z][a-z0-9-]{0,31}$"
                      },
                      "source": {
                        "oneOf": [
                          {
                            "type": "object",
                            "required": [
                              "type",
                              "image_id"
                            ],
                            "properties": {
                              "type": {
                                "const": "managed_image"
                              },
                              "image_id": {
                                "type": "string",
                                "pattern": "^img_[0-7][0-9A-HJKMNP-TV-Z]{25}$"
                              }
                            },
                            "additionalProperties": false
                          },
                          {
                            "type": "object",
                            "required": [
                              "type",
                              "path"
                            ],
                            "properties": {
                              "type": {
                                "const": "external"
                              },
                              "path": {
                                "type": "string",
                                "minLength": 1,
                                "description": "Absolute host path, subject to server-side realpath and ownership checks."
                              }
                            },
                            "additionalProperties": false
                          }
                        ]
                      },
                      "writable": {
                        "type": "boolean"
                      }
                    },
                    "additionalProperties": false
                  }
                },
                "networks": {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "required": [
                          "id",
                          "mode"
                        ],
                        "properties": {
                          "id": {
                            "type": "string",
                            "pattern": "^[a-z][a-z0-9-]{0,31}$"
                          },
                          "mode": {
                            "const": "shared"
                          },
                          "mac_address": {
                            "type": "string",
                            "pattern": "^(?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$",
                            "description": "Stable locally administered MAC. The server assigns one when omitted."
                          }
                        },
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "required": [
                          "id",
                          "mode"
                        ],
                        "properties": {
                          "id": {
                            "type": "string",
                            "pattern": "^[a-z][a-z0-9-]{0,31}$"
                          },
                          "mode": {
                            "const": "none"
                          }
                        },
                        "additionalProperties": false
                      }
                    ]
                  }
                },
                "graphics": {
                  "type": "object",
                  "required": [
                    "enabled"
                  ],
                  "properties": {
                    "enabled": {
                      "type": "boolean"
                    },
                    "width": {
                      "type": "integer",
                      "minimum": 320,
                      "maximum": 8192
                    },
                    "height": {
                      "type": "integer",
                      "minimum": 200,
                      "maximum": 8192
                    },
                    "pixels_per_inch": {
                      "type": "integer",
                      "minimum": 72,
                      "maximum": 600,
                      "default": 144
                    }
                  },
                  "allOf": [
                    {
                      "if": {
                        "properties": {
                          "enabled": {
                            "const": true
                          }
                        },
                        "required": [
                          "enabled"
                        ]
                      },
                      "then": {
                        "required": [
                          "width",
                          "height"
                        ]
                      }
                    }
                  ],
                  "additionalProperties": false
                },
                "serial": {
                  "type": "object",
                  "required": [
                    "enabled",
                    "capture"
                  ],
                  "properties": {
                    "enabled": {
                      "type": "boolean"
                    },
                    "capture": {
                      "type": "boolean"
                    }
                  },
                  "additionalProperties": false
                },
                "guest_agent": {
                  "type": "object",
                  "required": [
                    "enabled",
                    "required_for_ready"
                  ],
                  "properties": {
                    "enabled": {
                      "type": "boolean"
                    },
                    "required_for_ready": {
                      "type": "boolean"
                    },
                    "vsock_port": {
                      "type": "integer",
                      "minimum": 1024,
                      "maximum": 4294967295,
                      "default": 10777
                    }
                  },
                  "allOf": [
                    {
                      "if": {
                        "properties": {
                          "enabled": {
                            "const": false
                          }
                        },
                        "required": [
                          "enabled"
                        ]
                      },
                      "then": {
                        "properties": {
                          "required_for_ready": {
                            "const": false
                          }
                        }
                      }
                    }
                  ],
                  "additionalProperties": false
                },
                "restart_policy": {
                  "enum": [
                    "never",
                    "on_failure",
                    "always"
                  ]
                },
                "autostart": {
                  "type": "boolean"
                }
              },
              "additionalProperties": false
            },
            "wait": {
              "type": "object",
              "required": [
                "condition",
                "timeout_seconds"
              ],
              "properties": {
                "condition": {
                  "enum": [
                    "runtime_running",
                    "guest_agent_ready",
                    "guest_service_ready"
                  ]
                },
                "service_name": {
                  "type": "string",
                  "minLength": 1
                },
                "timeout_seconds": {
                  "type": "number",
                  "exclusiveMinimum": 0,
                  "maximum": 86400
                }
              },
              "allOf": [
                {
                  "if": {
                    "properties": {
                      "condition": {
                        "const": "guest_service_ready"
                      }
                    }
                  },
                  "then": {
                    "required": [
                      "service_name"
                    ]
                  }
                }
              ],
              "additionalProperties": false
            },
            "steps": {
              "type": "array",
              "minItems": 1,
              "maxItems": 256,
              "items": {
                "type": "object",
                "required": [
                  "type",
                  "argv",
                  "timeout_seconds"
                ],
                "properties": {
                  "type": {
                    "const": "guest.exec"
                  },
                  "name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 128
                  },
                  "argv": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                      "type": "string"
                    }
                  },
                  "cwd": {
                    "type": "string",
                    "default": "/"
                  },
                  "env": {
                    "type": "object",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "timeout_seconds": {
                    "type": "number",
                    "exclusiveMinimum": 0,
                    "maximum": 86400
                  }
                },
                "additionalProperties": false
              }
            },
            "timeout_seconds": {
              "type": "number",
              "exclusiveMinimum": 0,
              "maximum": 172800
            },
            "cleanup": {
              "enum": [
                "delete_on_success",
                "always_delete",
                "retain"
              ]
            },
            "retain_on_failure": {
              "type": "boolean"
            }
          },
          "additionalProperties": false
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "idempotency_key",
        "body"
      ],
      "additionalProperties": false
    }
  },
  "test_status": {
    "name": "test_status",
    "description": "Get a persistent TestRun. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "test_run_id": {
          "type": "string",
          "pattern": "^tr_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "tr_01J00000000000000000000000"
          ]
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "test_run_id"
      ],
      "additionalProperties": false
    }
  },
  "test_artifacts": {
    "name": "test_artifacts",
    "description": "List artifacts collected for one TestRun. Only the public API is used. Mutations return durable Operations; reuse idempotency_key on retry.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "test_run_id": {
          "type": "string",
          "pattern": "^tr_[0-7][0-9A-HJKMNP-TV-Z]{25}$",
          "examples": [
            "tr_01J00000000000000000000000"
          ]
        },
        "cursor": {
          "type": "string",
          "minLength": 1,
          "maxLength": 512
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "maximum": 200,
          "default": 50
        },
        "request_timeout_seconds": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 86400,
          "description": "Local HTTP deadline; 30 seconds by default. VM waits default to their explicit body timeout plus five seconds."
        }
      },
      "required": [
        "test_run_id"
      ],
      "additionalProperties": false
    }
  }
}
''';
