name: gaovmd
description: GaoVM daemon control plane
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.9.0
dependencies:
  crypto: ^3.0.6
  ffi: ^2.1.4
  gaovm_models:
    path: ../../libs/gaovm_models
  gaovm_rpc:
    path: ../../libs/gaovm_rpc
  sqlite3: ^2.9.4
dev_dependencies:
  test: ^1.25.0
